In [3]:
import numpy as np
import tensorflow as tf

In [8]:
x = np.array(2)
x.shape

0

In [16]:
y = np.array([1,2])
y.shape

(2,)

In [25]:
z = np.array([[-1,2,3],
              [3,4,5]])
z.shape
z.shape

(2, 3)

In [28]:
w = np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])
w.shape


(2, 2, 3)

In [23]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [26]:
naive_relu(z)

array([[0, 2, 3],
       [3, 4, 5]])

In [27]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [29]:
v = np.array([[7, 8, 9],
              [10, 11, 12]])

In [30]:
naive_add(z, v)

array([[ 6, 10, 12],
       [13, 15, 17]])

In [31]:
import time

In [39]:
x = np.random.random((20, 100))
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z, 0.)
t1 = time.time()
print("Vectorized version: %f seconds" % (t1 - t0))

t2 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
t3 = time.time()
print("Naive version: %f seconds" % (t3 - t2))


Vectorized version: 0.012146 seconds
Naive version: 1.657449 seconds


In [42]:
A = np.random.random((32, 10))
b = np.random.random((10,))

b = np.expand_dims(b, axis=0)
b.shape


(1, 10)

In [44]:
B = np.concatenate([b] * 32, axis=0)
B.shape

(32, 10)

In [45]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [47]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([1, 2])
naive_add_matrix_and_vector(x, y)

array([[2, 4],
       [4, 6]])

In [48]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
z.shape

(64, 3, 32, 10)

In [51]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)
print(x)
print(y)
print(z)

[0.52105226 0.87666829 0.62926254 0.28950919 0.06325177 0.56998732
 0.92469323 0.10468054 0.79432369 0.88092596 0.61301091 0.10738974
 0.74350137 0.20137366 0.75637048 0.90654844 0.98305312 0.40684916
 0.43227564 0.42480658 0.88878975 0.70654758 0.03420572 0.22252645
 0.50590084 0.4364481  0.49629987 0.00845462 0.23803342 0.53845544
 0.367019   0.82094759]
[0.83587135 0.78280186 0.20623463 0.69804845 0.44612921 0.43711701
 0.66479639 0.01237058 0.12662672 0.83504204 0.15820763 0.66551139
 0.43918729 0.28834517 0.38485647 0.34032337 0.28550246 0.84057408
 0.39901496 0.84130446 0.80488805 0.06401842 0.99957512 0.89468941
 0.30148168 0.07837063 0.82727172 0.09777112 0.68091752 0.50284708
 0.09210093 0.85168429]
8.246292216780319


In [52]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(x.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [53]:
x = np.array([1, 2])
y = np.array([3, 4])
naive_vector_dot(x, y)

11.0

In [54]:
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [56]:
x = np.array([[1, 2, 3],
              [3, 4, 5]])
y = np.array([1, 2, 3])
naive_matrix_vector_dot(x, y)

array([14., 26.])

In [57]:
def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z

In [58]:
naive_matrix_vector_dot(x, y)

array([14., 26.])

In [ ]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z
